#!/usr/bin/env python

import numpy
import argparse
import sys

parser = argparse.ArgumentParser(description='Create a linearly interpolated time map')
parser.add_argument('width', action='store', type=int)
parser.add_argument('height', action='store', type=int)
parser.add_argument('start_time', action='store', type=float)
parser.add_argument('end_time', action='store', type=float)
parser.add_argument('output_file', action='store', type=str)

result = parser.parse_args()

single_time_slice = numpy.linspace(result.start_time, result.end_time, num=result.height, endpoint=True).astype('float32')

numpy.repeat(single_time_slice, result.width).reshape((result.height, result.width)).tofile(result.output_file)

